language: python
env:
  global:
  - JEKYLL_ENV=production
  - PLACE=za-wc011
  - secure: w24froAFw+Z6YK6HlwdmnCXdMjF4AZN0ugT4Pzvf2VyZfev0asMocNbVZf/nekMPGPgyvkjm7c8BNn4D5Omf7DQ4XmAVso6ODO+M7Ybrk0c/Acg6tXufBKmxYuHAHaQ1FNUg4q04ebUT5sJy9VCcmjQUN3rKPsmWP0n/Xgkm4/bz/wp4omTh9GbtulIYE8b0iIhYXd01320Y3rHuZAb+ng3+VBtCPBmtpA0ZT63wrl5iyx6F0cs/YKpw08vms1uos4VeZtT6vn3a0UgStonZj4eGpSPLP1ENPWjWCojn+0mzRkqFSPKC4Qih7ODepK7/xkbhVV1sYpCYHT0g0yQIkH3LFtIY5MGZDGIlA5s1fYAW19iP4meOS6zeO3LoyBDU6BcHpC/g7WP0V9ezCWm/oUqdrgrKFMyNkyWFmV2BO+ZWPhOMrm56plc67anX6czwnQyzRCsLHNZZOuKjgkxErBKKaqnXIVtvo9Qt9bUxKvSzEKxzxpTq6x0InBi02qFOLAcmEpO6/PV1jYgClSf8Te/crBQvD07m/x2d9cpYyzrqVJ946gKmaCNXBqv3N4x4BTBwhWVsI3eQ5XdtmUqmuPE/PbHB/2xsSZTk7CphLKGfuEOwFR4RqwjOhrOkrje813ECyXc5HxRw5C32kdJ4wpa3gd6Vnjy1+ZxT4EyDAIA=
  - secure: Va3q7lfXu7KMqMw2Jx03Y9k2w7CxBlf59NytahOwWZlLsYQ628CUNmuxPQoANyr5btU8t96Tyl/0tZOlY5hk4RUWIcv0GG9HJmHsNAMiYzdopbHDKgg9qF3gXxvximxFk9WTLJ7xF1h2Honc0uJ357X6atJ7E0Y7fZ76vGevbUAfHNECjStjgqwN5MHmsEpl6X2uRBZHFVX9C6LEW+h7vJX8q9lhl2zj+0c+qYGQvs7ET4kI/i8NS5V1XJh7kcvZ50QAqnl2wHUh41e5U8zmHGZG+snaQSRbCdwmF4/kSRO+66PC1JnhlspPCMfkwCYCWEiTQv5RWT/ZRP/9XL+ONJ/RNjSrR5qM1MUVFG7oLnjQ9712BPr/xO8k0Nu10Hi1JJAjt3OVM00kw9CazZFBwqW/xi3wfrXaEN6FkaxqZ1zAlw9bwspYGlhI/mKk/+Szn6e2lfcCjMP5eqeGXBxBwe8i3lrc2cbZp89lhyqrk700xSdApknDSmSe9dmHxVdS745EsK4ZNnaSKUS/2z1Pe6bITm950Ol70HA3u6ZzcdBpUzPoDtht9u4g/Yncc7rJE4tpgSeUtjqQMkuErxUSiYGcu6dwEgrwyQjLWLCSvK+iYgaGpNFuM5hB/u+8s/5oE5T2RLDsR0r8t7DK7QPrMysL4oRp4EUME579LPbD+/Q=
install:
- git clone --depth 1 https://github.com/laws-africa/openbylaws-microsite.git build
- cd build
- pip install -r requirements.txt
- bundle install
- python bin/place.py $PLACE
script: bundle exec jekyll build --trace
deploy:
  provider: pages
  local_dir: build/_site
  target_branch: gh-pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  fqdn: matzikama.openbylaws.org.za
  on:
    branch: master
