language: python
env:
  global:
  - JEKYLL_ENV=production
  - PLACE=za-ec443
  - secure: b4O/YlO5jjR5fXTmz6S7HaSI3Gg5bdqfwBsUv0jOLehYLLx7rrlav0EQ9HXaMJS/V4pm/H5wMZ1jUxY+G0axzX8pIHlrK5wyGXr4CbLofmRZsSjYubNM6ZD/l4VHvaUwY/3B3fDJJJekCxdfLD3v66YUccT0YT4cUDVW9GtaKuyOzkMkAiRP5AUDQirA7/mi9ve8D7iG50TFHqDS3U6fytDAzj21Qxqv4dCG9EBugeLmdhiXxPQHSzGgd5ZINyNOAbuu9SH3ZFpvYDbiTWdTEyvQUaT1ruwuFW9Xmtk/wlel88ej2I88VKWmC6lc2Opt9g1aixzywNPydUuZ7/t0aomES0T1N1MSebbsdkpTzhYm6nT/k9dlvQnBKdw/7xnVA1ZpV3NywXQ4VwTFngz596lZWthUKpHpOAkgGUXCda4WY1TmCa/E1Z9qxd8g8gA1FmWjx+cWWvP7VcWwveyyMZ70m48e14+5uidDcMxg7z410YUuUKHP9Ub9Zv8eyRqWJVK3bDlG9A2Yb95UBhEE8USWEfjuDbpUFgFWPlvGBo6knHSl9wuvO2oKEf/9ho61q1XQnZw9ZcxR9AVvxwKM0nXgjxymxF54MS5hlOPOt2ads+/axKortOhKW4Qaw6Lp6e9lmUlqrpO/IBUYZvOVBXV8qoL5Np/e5HJDTejT75c=
  - secure: Sjgxk09aRgnSLVDXA3pgPKaKtRQkVuwlSQ5ot57N/xCwGIrm5TE0RaqEgwXMBAwoGICQaRp0fVEJ9oiMI66RVt8i8Nkx/47S07dDahKv1XSPYVoj/HC0aAS+tlIF49Qg8CG3CPZUPZIITziT7JE/DfU4SmZITSCd58Jn/BMG6p7tPFGz3VlhTd8GeOuX21q6gX/NxEx0tkKbIN0ND4IMgQOwjra5YSxIG3aSkwPt5Z/QWyRBWaCHTVnlYjTK0HG/+Qvu1s1khp1ynJb0qK3v/aFqWv39KHnBlFlD7jwPe/zBhY3OkiPQ2aeYRGG+7hmJdLZEEkac5Zdau2W51btYpOjVPZfV1s7t9pTBzl2wr/3zBErDOR6uIUP10jv6arMBTgfTvuYzBxmpZ/VrThuWbq/qvG4Dy6qooV43jpQBkoPoLKynEYBHVQ60MQ9ja1a+gpTIfODwGRL3mPnBIfK1ipp6MN5/1OXxG2XAWAGii3WPI2PKAf2TdY3sK55RF8gMJGOsAM9lHS0Uzbay6FKErAQQ7V9ssMxGyhJj2nStuf+eflyzEj2DzcnJ0xo0Qcgp7wahmOhQFVpk5yQPxe1uMBuoCBZCDdD8TtZUxPw6DnMY1l0iEq7nJuiLkroJTTqxUT2bRMc8aDLTQ17Yq8gFI/VW0fAE0j8O02Antr3EOpI=
install:
- git clone --depth 1 https://github.com/laws-africa/openbylaws-microsite.git build
- cd build
- pip install -r requirements.txt
- bundle install
- python bin/place.py $PLACE
script: bundle exec jekyll build --trace
deploy:
  provider: pages
  local_dir: build/_site
  target_branch: gh-pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  fqdn: mbizana.openbylaws.org.za
  on:
    branch: master
